-- =============================================================================
-- sql/06_decision/01_decision_tables.sql
-- Purpose: Create immutable decision audit tables in the DECISION schema.
--          These tables record every recommendation shown, every human
--          decision (approve/modify/reject), and every follow-up created.
-- Role: ACCOUNTADMIN (DECISION schema owner) or C360_ADMIN
-- Idempotent: CREATE TABLE IF NOT EXISTS (safe rerun)
-- Cost: Zero. DDL only.
--
-- Immutability contract:
--   - C360_SERVICE_APP has INSERT + SELECT only (no UPDATE, no DELETE)
--   - C360_AUDITOR has SELECT only
--   - No role except ACCOUNTADMIN can DROP these tables
--   - These grants are already configured via FUTURE GRANTS in 07_security/01_grants.sql
--
-- Write pattern (from Streamlit app):
--   1. Rep views a customer → app INSERTs into RECOMMENDATION_LOG
--   2. Rep clicks Accept/Modify/Reject → app INSERTs into DECISION_AUDIT_EVENT
--   3. If Accept or Modify → app also INSERTs into FOLLOW_UP_LOG
--   All three writes happen in a single user action. No background jobs.
-- =============================================================================

USE ROLE ACCOUNTADMIN;
USE DATABASE CUSTOMER360_DB;
USE SCHEMA DECISION;
USE WAREHOUSE CUSTOMER360_WH;

-- =============================================================================
-- RECOMMENDATION_LOG
-- Grain: One row per recommendation shown to a representative.
-- Immutable: once written, never updated. If the same customer is looked up
--            again, a new row is created with a new recommendation_log_id.
-- Written by: Streamlit app (C360_SERVICE_APP) when the NBA panel renders.
-- =============================================================================
CREATE TABLE IF NOT EXISTS RECOMMENDATION_LOG (
    -- Primary key
    recommendation_log_id   VARCHAR(36)     NOT NULL
        COMMENT 'PK — UUID generated by the application via UUID_STRING()',

    -- Customer context
    customer_id             VARCHAR(20)     NOT NULL
        COMMENT 'FK → ANALYTICS.DIM_CUSTOMER. Which customer this recommendation is for.',

    -- Recommendation details
    recommendation_timestamp TIMESTAMP_NTZ  NOT NULL    DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'When the recommendation was generated and shown to the rep',
    action_type             VARCHAR(30)     NOT NULL
        COMMENT 'Action type code from ACTION_LIBRARY (e.g. complaint_followup)',
    action_name             VARCHAR(100)    NOT NULL
        COMMENT 'Human-readable action name (e.g. Complaint Follow-Up)',
    action_description      VARCHAR(2000)
        COMMENT 'Full action text shown to the representative',

    -- Scoring
    confidence_level        VARCHAR(20)     NOT NULL
        COMMENT 'high, medium_high, medium, or low',
    confidence_score        FLOAT
        COMMENT 'Numeric confidence 0.00–1.00',
    risk_tier               VARCHAR(20)
        COMMENT 'Customer risk tier at recommendation time: critical, high, medium, low',
    composite_risk_score    FLOAT
        COMMENT 'Numeric composite risk score at recommendation time',
    final_score             FLOAT
        COMMENT 'NBA final_score (relevance x safety)',

    -- Full payload for audit replay
    recommendation_payload  VARIANT
        COMMENT 'Complete recommendation context as JSON: evidence_signals, data_completeness, eligibility_check, alternatives',

    -- Provenance
    session_id              VARCHAR(200)
        COMMENT 'Streamlit session identifier for replay correlation',
    representative_id       VARCHAR(200)    DEFAULT CURRENT_USER()
        COMMENT 'Who was shown the recommendation (Snowflake username)',

    -- Audit
    created_at              TIMESTAMP_NTZ   NOT NULL    DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'When this row was written — immutable',
    _immutable              BOOLEAN         NOT NULL    DEFAULT TRUE
        COMMENT 'Always TRUE. Documents that this row must never be updated.',

    CONSTRAINT pk_recommendation_log PRIMARY KEY (recommendation_log_id)
)
COMMENT = 'Immutable log of every NBA recommendation shown to a representative. One row per recommendation event. Append-only — no UPDATE or DELETE permitted.';


-- =============================================================================
-- FOLLOW_UP_LOG
-- Grain: One row per approved or modified recommendation.
-- Written only when the rep clicks Accept or Modify — never for rejections.
-- Rejections are recorded in DECISION_AUDIT_EVENT only.
-- Immutable: once written, never updated.
-- Written by: Streamlit app (C360_SERVICE_APP) on Accept/Modify click.
-- =============================================================================
CREATE TABLE IF NOT EXISTS FOLLOW_UP_LOG (
    -- Primary key
    follow_up_id            VARCHAR(36)     NOT NULL
        COMMENT 'PK — UUID generated by the application via UUID_STRING()',

    -- Link to recommendation
    recommendation_log_id   VARCHAR(36)     NOT NULL
        COMMENT 'FK → RECOMMENDATION_LOG. Which recommendation this follow-up acts on.',

    -- Customer context
    customer_id             VARCHAR(20)     NOT NULL
        COMMENT 'FK → ANALYTICS.DIM_CUSTOMER. Denormalized for query convenience.',

    -- Decision details
    follow_up_status        VARCHAR(20)     NOT NULL
        COMMENT 'approved or modified — rejections go to DECISION_AUDIT_EVENT only',
    action_taken            VARCHAR(2000)   NOT NULL
        COMMENT 'The action the rep committed to. Equals recommendation if approved; modified text if modified.',
    notes                   VARCHAR(4000)
        COMMENT 'Rep modification notes or context. NULL if approved as-is.',

    -- Assignment
    assigned_to             VARCHAR(200)    DEFAULT CURRENT_USER()
        COMMENT 'Rep who approved/modified this action (Snowflake username)',

    -- Audit
    created_at              TIMESTAMP_NTZ   NOT NULL    DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'When this follow-up was created — immutable',
    _immutable              BOOLEAN         NOT NULL    DEFAULT TRUE
        COMMENT 'Always TRUE. Documents that this row must never be updated.',

    CONSTRAINT pk_follow_up_log PRIMARY KEY (follow_up_id)
)
COMMENT = 'Immutable log of committed actions (approved or modified). One row per human approval. Append-only — no UPDATE or DELETE.';


-- =============================================================================
-- DECISION_AUDIT_EVENT
-- Grain: One row per state transition in the decision lifecycle.
-- Captures ALL events: presented, approved, modified, rejected, timeout.
-- This is the complete audit trail. FOLLOW_UP_LOG is a subset (only commits).
-- Immutable: once written, never updated.
-- Written by: Streamlit app (C360_SERVICE_APP) on every decision interaction.
-- =============================================================================
CREATE TABLE IF NOT EXISTS DECISION_AUDIT_EVENT (
    -- Primary key
    event_id                VARCHAR(36)     NOT NULL
        COMMENT 'PK — UUID generated by the application via UUID_STRING()',

    -- Link to recommendation
    recommendation_log_id   VARCHAR(36)     NOT NULL
        COMMENT 'FK → RECOMMENDATION_LOG. Which recommendation this event relates to.',

    -- Customer context
    customer_id             VARCHAR(20)     NOT NULL
        COMMENT 'FK → ANALYTICS.DIM_CUSTOMER. Denormalized for query convenience.',

    -- Event details
    event_type              VARCHAR(20)     NOT NULL
        COMMENT 'presented, approved, modified, rejected, or timeout',
    event_timestamp         TIMESTAMP_NTZ   NOT NULL    DEFAULT CURRENT_TIMESTAMP()
        COMMENT 'When this event occurred',
    event_notes             VARCHAR(4000)
        COMMENT 'Rejection reason, modification summary, or other context',

    -- Actor
    actor                   VARCHAR(200)    DEFAULT CURRENT_USER()
        COMMENT 'Who performed this action (Snowflake username)',

    -- Extended metadata
    metadata                VARIANT
        COMMENT 'Additional structured context: action_name, confidence, risk_tier, modification_text',

    -- Audit
    _immutable              BOOLEAN         NOT NULL    DEFAULT TRUE
        COMMENT 'Always TRUE. Documents that this row must never be updated.',

    CONSTRAINT pk_decision_audit_event PRIMARY KEY (event_id)
)
COMMENT = 'Complete audit trail of all decision lifecycle events (presented, approved, modified, rejected, timeout). Append-only — no UPDATE or DELETE.';


-- =============================================================================
-- Verification
-- =============================================================================

-- Confirm tables exist
SELECT table_name, table_type, comment
FROM CUSTOMER360_DB.INFORMATION_SCHEMA.TABLES
WHERE table_schema = 'DECISION'
ORDER BY table_name;

-- Confirm grants propagated via FUTURE GRANTS
SHOW GRANTS ON TABLE CUSTOMER360_DB.DECISION.RECOMMENDATION_LOG;
SHOW GRANTS ON TABLE CUSTOMER360_DB.DECISION.FOLLOW_UP_LOG;
SHOW GRANTS ON TABLE CUSTOMER360_DB.DECISION.DECISION_AUDIT_EVENT;
